stages:
  - test

tree-sitter-tests:
  stage: test
  image: node:23.2
  before_script:
    - npm install tree-sitter-cli
  script:
    - tree-sitter generate
    - tree-sitter test
  # artifacts:
  #   when: always
  #   paths:
  #     - log.txt
  only:
    - main
    - develop

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
